name: basal-utuc-spatial
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10.11
  - r-base=4.3.1
  - r-seurat
  - r-harmony
  - r-dplyr
  - r-tidyr
  - r-readr
  - r-yaml
  - r-ggplot2
  - r-mass
  - r-mgcv
  - r-rann
  - r-fnn
  - r-survival
  - r-proc
  - r-survminer
  - r-timeroc
  - bioconductor-clusterprofiler
  - bioconductor-gsva
  - bioconductor-org.hs.eg.db
  - bioconductor-monocle
  - pip
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - scikit-image
  - statsmodels
  - pyyaml
  - anndata
  - scanpy
  - jupyter
  - pip:
      - cell2location
      - scvi-tools
      - squidpy
      - lifelines
